#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# API routes
create_team:
  path: /api/team
  controller: App\Controller\LeagueController::createTeamAction
  methods: [POST]

create_league:
  path: /api/league
  controller: App\Controller\LeagueController::createLeagueAction
  methods: [POST]

show_week:
  path: /api/show_week
  controller: App\Controller\LeagueController::showWeekAction
  methods: [GET]

show_leagues:
  path: /api/show_leagues
  controller: App\Controller\LeagueController::showLeaguesAction
  methods: [GET]

show_teams:
  path: /api/show_teams
  controller: App\Controller\LeagueController::showTeamsAction
  methods: [GET]

play_match:
  path: /api/play_match
  controller: App\Controller\LeagueController::playMatchAction
  methods: [GET]

play_all_match:
  path: /api/play_all_match
  controller: App\Controller\LeagueController::playAllMatchAction
  methods: [GET]

update_match:
  path: /api/update_match
  controller: App\Controller\LeagueController::updateMatchAction
  methods: [POST]
